# Contenu du fichier .streamlit/secrets.toml
GOOGLE_API_KEY = "AIzaSyAY4NqDYCpBAebXi3Qb-KMLXBPpuTfvPH0"

# Configuration SMTP (pour l'envoi d'email pro)
SMTP_HOST = "node38-eu.n0c.com"
SMTP_PORT = 465 # Attention, doit Ãªtre un nombre entier
SMTP_SENDER = "abdoulmagid.kanoma@novatech.ne"
SMTP_PASSWORD = "Sf1V.&QyBv" # Le mot de passe de votre compte pro